import enum


class Category(enum.Enum):
    games = 'games'
    high_risk = 'high risk'
    gambling = 'gambling'
    collectibles = 'collectibles'
    marketplaces = 'marketplaces'
    other = 'other'
    exchanges = 'exchanges'
    social = 'social'
    defi = 'defi'


class Protocol(enum.Enum):
    polygon = 'polygon'
    oasis = 'oasis'
    tron = 'tron'
    telosevm = 'telosevm'
    solana = 'solana'
    everscale = 'everscale'
    vulcanforged = 'vulcanforged'
    telos = 'telos'
    tezos = 'tezos'
    aurora = 'aurora'
    fuse = 'fuse'
    cronos = 'cronos'
    klaytn = 'klaytn'
    hedera = 'hedera'
    binance_smart_chain = 'binance-smart-chain'
    moonriver = 'moonriver'
    astar = 'astar'
    near = 'near'
    avalanche = 'avalanche'
    other = 'other'
    flow = 'flow'
    waves = 'waves'
    optimism = 'optimism'
    kardiachain = 'kardiachain'
    immutablex = 'immutablex'
    ethereum = 'ethereum'
    ontology = 'ontology'
    shiden = 'shiden'
    steem = 'steem'
    stacks = 'stacks'
    eos = 'eos'
    rsk = 'rsk'
    hive = 'hive'
    dep = 'dep'
    iotex = 'iotex'
    celo = 'celo'
    wax = 'wax'
    oec = 'oec'
    thundercore = 'thundercore'
    heco = 'heco'
    harmony = 'harmony'
    moonbeam = 'moonbeam'
    fantom = 'fantom'
    ronin = 'ronin'
    algorand = 'algorand'
